<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.537">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Colin Heeneman">
<meta name="dcterms.date" content="2025-03-03">

<title>Ghana Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GRPL2.0_files/libs/clipboard/clipboard.min.js"></script>
<script src="GRPL2.0_files/libs/quarto-html/quarto.js"></script>
<script src="GRPL2.0_files/libs/quarto-html/popper.min.js"></script>
<script src="GRPL2.0_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GRPL2.0_files/libs/quarto-html/anchor.min.js"></script>
<link href="GRPL2.0_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GRPL2.0_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GRPL2.0_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GRPL2.0_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GRPL2.0_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ghana Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Colin Heeneman </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="general-instructions" class="level1">
<h1>General Instructions</h1>
<p><em>You have 24 hours to complete this test. All necessary files for completing the test are included in the attached zip file. When you submit the test, we want to see a complete record of your work. Please attach do-files and any other files you think are necessary to evaluate your work.</em></p>
<p><em>Remember that you will be graded not only on your answers, but also on your process (such as the efficiency of your code and comments). This test is designed to assess logical reasoning and problem-solving in addition to coding skills, so if you’re unable to answer a question using Stata, please explain what steps you would have taken had you known the appropriate commands. In general, remember to explain your reasoning and give as complete an answer as you can.</em></p>
<p><em>Follow coding best practices to ensure your code is efficient, easily readable, and the results are reproducible even if the data set changes over time.</em></p>
<p><em>Using resources such as Stata’s internal help files and online resources is encouraged (and often necessary!), but please cite the resources you use, and do not consult with other people.</em></p>
<p><em>We have provided you with survey data collected from households in Ghana in two waves. These households were part of a Randomized Controlled Trial (RCT), where participants in treated households received Group Therapy to alleviate symptoms of depression.</em></p>
<p><em>To explore whether Group Therapy (GT) alleviates depression or not, an RCT was conducted in partnership with a local organization that provides GT sessions designed to improve mental health through guided discussions led by a trained facilitator. After Wave 1 of data collection was complete, half of the households in the sample were randomly selected to receive the opportunity to attend weekly GT sessions for a period of three months at no cost to participants. In each treatment household, the household head and their spouse were invited to GT sessions. For the purposes of this analysis, assume that there was perfect attendance at these sessions. Once all GT sessions were completed, Wave 2 data were collected (6 months after Wave 1).</em></p>
<p><em>This is a hypothetical treatment created for this exercise. The Ghana Panel Survey data has been slightly modified for this purpose.</em></p>
<p><em>Through the exercises below, you will prepare the data, conduct exploratory analysis, and present findings for the RCT.</em></p>
<p><em>There are three data sets, which include data collected at Wave 1 (before the intervention), and Wave 2 (after the intervention). The data sets are as follows:</em></p>
<ul>
<li><p><em>Demographics: This data set includes treatment assignment at the household level and demographic information for each member in the sampled households.</em></p></li>
<li><p><em>Assets: This data set includes the quantity and monetary value of assets owned by the household, under three categories of assets: Animals, Tools, and Durable Goods.</em></p></li>
<li><p><em>Depression Information: This data set includes information for the Kessler Psychological Distress Scale collected for household heads and their spouses.</em></p></li>
</ul>
<p><em>Note that these are imperfect data sets. Not all the variables are cleaned, so watch out for things like missing values, ordering of categories, and strings.</em></p>
</section>
<section id="part-1" class="level1">
<h1>Part 1</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># setting up for analysis by loading necessary libraries and data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a> <span class="co"># loading the libraries I will need for this analysis</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(summarytools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'summarytools'

The following object is masked from 'package:tibble':

    view</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a> <span class="co"># loading raw data sets naming them _raw</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>assets_raw <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"data/assets.dta"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>demographics_raw <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"data/demographics.dta"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>depression_raw <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"data/depression.dta"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a> <span class="co"># check the structure of the data sets</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(assets_raw)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(demographics_raw)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(depression_raw)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a> <span class="co"># Inspect the first few rows of each data set</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(assets_raw)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(demographics_raw)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(depression_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="q1" class="level2">
<h2 class="anchored" data-anchor-id="q1">Q1:</h2>
<p><em>At what level is each data set uniquely identified (i.e., what does each row represent, and which variables are unique identifiers)?</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># In order to answer this question, we need to inspect the structure of each datase and ID unique identifier(s) for each</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Q1 ANSWER:</strong></p>
<ul>
<li><p>Asset: Rows are individual <strong>assets</strong> owned by households. Unique identifiers are survey wave (<em>wave</em>) and household ID (<em>hhid</em>).</p></li>
<li><p>Demographics: Rows are demographic characteristics of <strong>individuals</strong>. Unique identifier is a combination of survey wave (<em>wave</em>) household ID (<em>hhid</em>) and household member ID (<em>hhmid</em>).</p></li>
<li><p>Depression: Rows are <strong>individuals</strong> once again, this time their responses on mental health survey in wave X. Unique identifier is a combination of survey wave (<em>wave</em>) household ID (<em>hhid</em>) and household member ID (<em>hhmid</em>).</p></li>
</ul>
<p><strong>Demographics</strong></p>
</section>
<section id="q2" class="level2">
<h2 class="anchored" data-anchor-id="q2">Q2:</h2>
<p><em>Import the demographics data set and calculate a proxy variable for household size based on the number of members surveyed in each household in Wave 1. Assume the household size for Wave 2 remains the same.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># calculate household size proxy</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>demographicsv1 <span class="ot">&lt;-</span> demographics_raw <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hhid, wave) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hh_size_proxy =</span> <span class="fu">ifelse</span>(wave <span class="sc">==</span> <span class="dv">1</span>, <span class="fu">n</span>(), <span class="cn">NA</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hhid) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hh_size_proxy =</span> <span class="fu">max</span>(hh_size_proxy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a> <span class="co"># display a summary of this variable</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(demographicsv1<span class="sc">$</span>hh_size_proxy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   3.000   5.000   5.244   7.000  20.000 </code></pre>
</div>
</div>
<p><strong>Q2 ANSWER:</strong></p>
<p>Household size was determined here using count from Wave 1 data, and assuming it holds constant for Wave 2. Unsurprisingly, the minimum value was 1 with the median being 5 and maximum of 20!</p>
<p><strong>Assets</strong></p>
<p><em>Asset data is useful as a proxy for wealth. This data set contains information on the quantity and monetary value of each individual asset owned by surveyed households.</em></p>
<p><em>Through the questions below, you will aggregate this information to estimate a monetary value for three asset categories.</em></p>
</section>
<section id="q3" class="level2">
<h2 class="anchored" data-anchor-id="q3">Q3:</h2>
<p><em>To calculate the monetary value of all assets, you should use the ‘currentvalue’ variable, which reports the monetary value of a single unit of the asset. However, you will notice that this variable is often missing. Please use the median of “current- value” for each type of asset (by type we mean, for example, “chickens”, “Cutlass”, “Room Furniture”, “Radio”, “Cell (mobile) Phone handset”, etc.) to impute the missing values.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># impute missing 'currentvalue' with the median for each asset type</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>assetsv1 <span class="ot">&lt;-</span> assets_raw <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Asset_Type) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">currentvalue =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(currentvalue), <span class="fu">median</span>(currentvalue, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), currentvalue)) <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a> <span class="co"># display summary of the imputed 'currentvalue'</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(assetsv1<span class="sc">$</span>currentvalue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
     0.0     15.0     50.0    175.3     50.0 100000.0 </code></pre>
</div>
</div>
<p><strong>Q3 ANSWER:</strong></p>
<p>Missing values for <em>currentvalue</em> of assets were imputed by using the median for each asset type. Overall, the median asset value was 50 units and the maximum value was 100,000.</p>
</section>
<section id="q4" class="level2">
<h2 class="anchored" data-anchor-id="q4">Q4:</h2>
<p><em>Create a variable that contains the total monetary value for each observation, by multiplying quantity and the imputed current value.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># create total monetary value variable</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>assetsv2 <span class="ot">&lt;-</span> assetsv1 <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_value =</span> quantity <span class="sc">*</span> currentvalue)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># display summary of the new variable</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(assetsv2<span class="sc">$</span>total_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
       0       30       50     1383      150 10000000 </code></pre>
</div>
</div>
<p><strong>Q4 ANSWER:</strong></p>
<p>After creating a column for total asset value for each asset observation, the median remained at 50 units and maximum increased to 10 million.</p>
</section>
<section id="q5" class="level2">
<h2 class="anchored" data-anchor-id="q5">Q5:</h2>
<p><em>Produce a data set at the household-wave level (for each household, there should be at most two observations, one for each wave) which contains the following variables:</em></p>
<ul>
<li><p><em>Household ID (hhid)</em></p></li>
<li><p><em>Wave ID (wave)</em></p></li>
<li><p><em>Total value of animals</em></p></li>
<li><p><em>Total value of tools</em></p></li>
<li><p><em>Total value of durable goods</em></p></li>
<li><p><em>Total asset value</em></p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># categorize assets into animals, tools, and durable goods</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>assetsv3 <span class="ot">&lt;-</span> assetsv2 <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">category =</span> <span class="fu">case_when</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(animaltype) <span class="sc">~</span> <span class="st">"animals"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(toolcode) <span class="sc">~</span> <span class="st">"tools"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(durablegood_code) <span class="sc">~</span> <span class="st">"durable_goods"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"other"</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a> <span class="co"># aggregate data at household-wave level</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>assetsv4 <span class="ot">&lt;-</span> assetsv3 <span class="sc">%&gt;%</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hhid, wave) <span class="sc">%&gt;%</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_value_animals =</span> <span class="fu">sum</span>(total_value[category <span class="sc">==</span> <span class="st">"animals"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_value_tools =</span> <span class="fu">sum</span>(total_value[category <span class="sc">==</span> <span class="st">"tools"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_value_durable_goods =</span> <span class="fu">sum</span>(total_value[category <span class="sc">==</span> <span class="st">"durable_goods"</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_asset_value =</span> <span class="fu">sum</span>(total_value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a> <span class="co"># display the processed data set</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(assetsv4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,357 × 6
   hhid        wave total_value_animals total_value_tools total_value_durable_…¹
   &lt;chr&gt;      &lt;dbl&gt;               &lt;dbl&gt;             &lt;dbl&gt;                  &lt;dbl&gt;
 1 0101001002     1                 250               8                    1500 
 2 0101001002     2                 180              11.5                  9325 
 3 0101001003     1                   0             269                    1614.
 4 0101001003     2                   0             774                   18382 
 5 0101001004     1                1000              48                    2550 
 6 0101001004     2                   0              92                    2413 
 7 0101001009     1                   0               4                     950 
 8 0101001009     2                   0              94                  103311 
 9 0101001010     1                   0               6                    2900 
10 0101001010     2                   0              20                   44945 
# ℹ 9,347 more rows
# ℹ abbreviated name: ¹​total_value_durable_goods
# ℹ 1 more variable: total_asset_value &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Q5 ANSWER:</strong></p>
<p>Data set has been restructured such that each household’s asset values were aggregated in the three categories: animals, tools, and durable goods.</p>
<p><strong>Mental Health / Depression Data</strong></p>
</section>
<section id="q6" class="level2">
<h2 class="anchored" data-anchor-id="q6">Q6:</h2>
<p><em>A Kessler-10 scale is a measure of mental health that uses 10 questions that identify how often people experience symptoms associated with depression. Using this reference, construct the kessler score (name it kessler_score) and a categorical variable named kessler categories with 4 categories: no significant depression, milddepression, moderate depression, and severe depression.Be careful: sometimes variables in the Kessler section are missing, which can complicate construction of a score. Please justify, using comments in your code, how you handle missing values.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># define the Kessler-10 variables</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>kessler_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"tired"</span>, <span class="st">"nervous"</span>, <span class="st">"sonervous"</span>, <span class="st">"hopeless"</span>, <span class="st">"restless"</span>,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"sorestless"</span>, <span class="st">"depressed"</span>, <span class="st">"everythingeffort"</span>, <span class="st">"nothingcheerup"</span>, <span class="st">"worthless"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># handle missing values:</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a> <span class="co"># if at least 8 out of 10 responses are available, replace missing with the mean of           available responses, this seems like a fair approach</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>depressionv1 <span class="ot">&lt;-</span> depression_raw <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">available_values =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">c_across</span>(<span class="fu">all_of</span>(kessler_vars)))),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">kessler_score =</span> <span class="fu">ifelse</span>(available_values <span class="sc">&gt;=</span> <span class="dv">8</span>, </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">sum</span>(<span class="fu">c_across</span>(<span class="fu">all_of</span>(kessler_vars)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">10</span> <span class="sc">/</span> available_values, </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>                           <span class="cn">NA_real_</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>available_values) <span class="co"># Remove intermediate calculation column</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a> <span class="co"># categorize Kessler scores into depression levels</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>mentalhealth <span class="ot">&lt;-</span> depressionv1 <span class="sc">%&gt;%</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">kessler_categories =</span> <span class="fu">case_when</span>(</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>      kessler_score <span class="sc">&lt;</span> <span class="dv">20</span> <span class="sc">~</span> <span class="st">"No significant depression"</span>,</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>      kessler_score <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">&amp;</span> kessler_score <span class="sc">&lt;</span> <span class="dv">25</span> <span class="sc">~</span> <span class="st">"Mild depression"</span>,</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>      kessler_score <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> kessler_score <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"Moderate depression"</span>,</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>      kessler_score <span class="sc">&gt;=</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"Severe depression"</span>,</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span>  <span class="co"># Assign NA if score couldn't be computed</span></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a> <span class="co"># display summary of results</span></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mentalhealth<span class="sc">$</span>kessler_score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  10.00   14.00   18.00   18.92   23.00   50.00      28 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mentalhealth<span class="sc">$</span>kessler_categories, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          Mild depression       Moderate depression No significant depression 
                     3190                      1651                      8119 
        Severe depression                      &lt;NA&gt; 
                      854                        28 </code></pre>
</div>
</div>
<p><strong>Q6 ANSWER:</strong></p>
<p>Kessler-10 score was calculated using the depression data set and categories created for ‘No significant depression’, ‘Mild depression’, ‘Moderate depression’ and ‘Severe depression’. Kessler 10 scores ranged from the minimum scale value of 10 to maximum scale value of 50, with the median being 18. A plurality of individuals fall into the ‘No significant depression’ category with the second most common being ‘Mild depression’.</p>
<p><strong>Constructing a single data set</strong></p>
</section>
<section id="q7" class="level2">
<h2 class="anchored" data-anchor-id="q7">Q7:</h2>
<p><em>At this point you have created three data sets: demographics, assets, and mentalhealth. Please combine all three of these data sets to create a single data set that you will use for data exploration and analysis. The unit of observation in this data set should be an individual in a given survey round. (There should be at most two observations per individual, one for Wave 1 and another for Wave 2).</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first I will convert hhid to character in all data sets to ensure compatibility</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="do">## doing this because initially got this error </span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>   <span class="co">#Error in `left_join()`:</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>   <span class="co">#! Can't join `x$hhid` with `y$hhid` due to incompatible types.</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>   <span class="co">#ℹ `x$hhid` is a &lt;double&gt;.</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>   <span class="co">#ℹ `y$hhid` is a &lt;character&gt;.</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a> <span class="co"># ensuring all key columns (`hhid`, `hhmid`, `wave`) have the same type so that they are      merged properly</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>demographicsv2 <span class="ot">&lt;-</span> demographicsv1 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(hhid, hhmid, wave), as.character))</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>mentalhealthv2 <span class="ot">&lt;-</span> mentalhealth <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(hhid, hhmid, wave), as.character))</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>assetsv5 <span class="ot">&lt;-</span> assetsv4 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(hhid, wave), as.character)) </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a> <span class="co"># standardize hhid formatting, ensure leading zeros are consistent as the assets data         contained a leading 0 before hhid </span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>demographics <span class="ot">&lt;-</span> demographicsv2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">hhid =</span> <span class="fu">str_pad</span>(hhid, <span class="at">width =</span> <span class="fu">max</span>(<span class="fu">nchar</span>(assetsv5<span class="sc">$</span>hhid)), <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>mentalhealthv3 <span class="ot">&lt;-</span> mentalhealthv2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">hhid =</span> <span class="fu">str_pad</span>(hhid, <span class="at">width =</span> <span class="fu">max</span>(<span class="fu">nchar</span>(assetsv5<span class="sc">$</span>hhid)), <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>assets <span class="ot">&lt;-</span> assetsv5 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">hhid =</span> <span class="fu">str_pad</span>(hhid, <span class="at">width =</span> <span class="fu">max</span>(<span class="fu">nchar</span>(demographicsv2<span class="sc">$</span>hhid)), <span class="at">pad =</span> <span class="st">"0"</span>))</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a> <span class="co"># make use of inner_join() to merge datasets based on relevant keys</span></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>mergedv1<span class="ot">&lt;-</span> <span class="fu">inner_join</span>(demographics, mentalhealthv3, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"hhid"</span>, <span class="st">"hhmid"</span>, <span class="st">"wave"</span>))</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>mergedv2 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(mergedv1, assets, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"hhid"</span>, <span class="st">"wave"</span>))</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a> <span class="co"># print the first few rows to check if all values are merging correctly</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mergedv2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 36
  wave  hhid   hhmid villageid treat_hh gender    age relationship maritalstatus
  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt; &lt;dbl+lb&gt; &lt;dbl+l&gt; &lt;dbl&gt; &lt;dbl+lbl&gt;    &lt;dbl+lbl&gt;    
1 1     01010… 1             1 0 [Cont… 1 [Mal…    35 1 [Househol… 1 [Married]  
2 1     01010… 2             1 0 [Cont… 5 [Fem…    31 2 [Spouse]   1 [Married]  
3 2     01010… 1             1 0 [Cont… 1 [Mal…    35 1 [Househol… 1 [Married]  
4 2     01010… 2             1 0 [Cont… 5 [Fem…    31 2 [Spouse]   1 [Married]  
5 1     01010… 1             1 1 [Trea… 1 [Mal…    28 1 [Househol… 1 [Married]  
6 2     01010… 1             1 1 [Trea… 1 [Mal…    29 1 [Househol… 1 [Married]  
# ℹ 27 more variables: spouseinhouse &lt;dbl+lbl&gt;, agemarried &lt;dbl&gt;,
#   religion &lt;dbl+lbl&gt;, religionother &lt;chr&gt;, fatherinhouse &lt;dbl+lbl&gt;,
#   fathereduc &lt;dbl+lbl&gt;, fathereducother &lt;chr&gt;, motherinhouse &lt;dbl+lbl&gt;,
#   mothereduc &lt;dbl+lbl&gt;, mothereducother &lt;chr&gt;, hh_size_proxy &lt;int&gt;,
#   tired &lt;dbl+lbl&gt;, nervous &lt;dbl+lbl&gt;, sonervous &lt;dbl+lbl&gt;,
#   hopeless &lt;dbl+lbl&gt;, restless &lt;dbl+lbl&gt;, sorestless &lt;dbl+lbl&gt;,
#   depressed &lt;dbl+lbl&gt;, everythingeffort &lt;dbl+lbl&gt;, …</code></pre>
</div>
</div>
<p><strong>Q7 ANSWER:</strong></p>
<p>Demographics, assets, and mentalhealth have been merged into a single data set ‘mergedv2’. Our ultimate data set for analysis contains the individual as the unit of observation, with a maximum of two observations for each (wave 1 and wave 2).</p>
</section>
</section>
<section id="part-2-exploratory-analysis" class="level1">
<h1>Part 2: Exploratory Analysis</h1>
<p><em>Using Wave 1 data, conduct exploratory analysis to understand the relationship between depression and household and demographic characteristics among individuals in Ghana. Specifically, do the following:</em></p>
<section id="q1-1" class="level2">
<h2 class="anchored" data-anchor-id="q1-1">Q1:</h2>
<p><em>Explore the relationship between depression and:</em></p>
<ol type="1">
<li><p><em>Household wealth, proxied by total asset value.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># just wave 1 data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for Wave 1 data</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>wave1 <span class="ot">&lt;-</span> mergedv2 <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(wave <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values in key variables</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wave1<span class="sc">$</span>kessler_score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  10.00   15.00   20.00   20.35   24.00   50.00      28 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wave1<span class="sc">$</span>total_asset_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      2    1400    2550   11152    4961 5791358 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot: Kessler Score vs. Household Wealth</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wave1, <span class="fu">aes</span>(<span class="at">x =</span> total_asset_value, <span class="at">y =</span> kessler_score)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  <span class="co"># Transparency to avoid overplotting</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span>  <span class="co"># Linear trend line</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Household Wealth and Depression"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Total Asset Value (Household Wealth Proxy)"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kessler Score (Depression)"</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GRPL2.0_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation test between wealth and depression</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(wave1<span class="sc">$</span>total_asset_value, wave1<span class="sc">$</span>kessler_score, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  wave1$total_asset_value and wave1$kessler_score
t = -0.34813, df = 7410, p-value = 0.7278
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.02680802  0.01872392
sample estimates:
         cor 
-0.004044145 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression: Predicting depression based on household wealth</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>model.wealth <span class="ot">&lt;-</span> <span class="fu">lm</span>(kessler_score <span class="sc">~</span> total_asset_value, <span class="at">data =</span> wave1)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.wealth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kessler_score ~ total_asset_value, data = wave1)

Residuals:
    Min      1Q  Median      3Q     Max 
-10.351  -5.350  -0.351   3.650  29.649 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        2.035e+01  7.360e-02 276.509   &lt;2e-16 ***
total_asset_value -2.139e-07  6.144e-07  -0.348    0.728    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.309 on 7410 degrees of freedom
  (28 observations deleted due to missingness)
Multiple R-squared:  1.636e-05, Adjusted R-squared:  -0.0001186 
F-statistic: 0.1212 on 1 and 7410 DF,  p-value: 0.7278</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a> <span class="co">#--------------------------------------------------------------------#</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a> <span class="co"># now restricting by removing outliers in total asset value (essentially getting rid of uber-wealthy because they may skew results)</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># Define percentile thresholds</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>lower_threshold <span class="ot">&lt;-</span> <span class="dv">0</span>  <span class="co"># Set lower threshold to 0</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>upper_threshold <span class="ot">&lt;-</span> <span class="fu">quantile</span>(wave1<span class="sc">$</span>total_asset_value, <span class="fl">0.90</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  <span class="co"># 90th percentile</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Restrict data: Remove values above the 90th percentile and ensure values are non-negative</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>wave1_restricted <span class="ot">&lt;-</span> wave1 <span class="sc">%&gt;%</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_asset_value <span class="sc">&gt;=</span> lower_threshold <span class="sc">&amp;</span> total_asset_value <span class="sc">&lt;=</span> upper_threshold)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Check summary after restriction</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wave1_restricted<span class="sc">$</span>total_asset_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.5  1300.0  2287.0  2996.2  3917.0 12069.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot: Kessler Score vs. Household Wealth (restricted data)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wave1_restricted, <span class="fu">aes</span>(<span class="at">x =</span> total_asset_value, <span class="at">y =</span> kessler_score)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  <span class="co"># Transparency to avoid overplotting</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span>  <span class="co"># Linear trend line</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Household Wealth and Depression (Restricted Data)"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Total Asset Value (Household Wealth Proxy)"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kessler Score (Depression)"</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GRPL2.0_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation test (restricted data)</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(wave1_restricted<span class="sc">$</span>total_asset_value, wave1_restricted<span class="sc">$</span>kessler_score, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  wave1_restricted$total_asset_value and wave1_restricted$kessler_score
t = -3.0653, df = 6667, p-value = 0.002183
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.06146011 -0.01352533
sample estimates:
       cor 
-0.0375143 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear regression (restricted data)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>model.wealth2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kessler_score <span class="sc">~</span> total_asset_value, <span class="at">data =</span> wave1_restricted)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.wealth2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kessler_score ~ total_asset_value, data = wave1_restricted)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.5326  -5.1812  -0.8122   3.8426  29.4905 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        2.056e+01  1.230e-01 167.101  &lt; 2e-16 ***
total_asset_value -9.800e-05  3.197e-05  -3.065  0.00218 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.305 on 6667 degrees of freedom
  (27 observations deleted due to missingness)
Multiple R-squared:  0.001407,  Adjusted R-squared:  0.001258 
F-statistic: 9.396 on 1 and 6667 DF,  p-value: 0.002183</code></pre>
</div>
</div></li>
</ol>
<!-- -->
<ol start="2" type="1">
<li><p><em>A household or demographic characteristic that seems interesting to you. Present the results from your exploration through tables, plots, a write-up, or anything else you think would be useful.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Age</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ensure only positive ages included</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>wave1_restricted <span class="ot">&lt;-</span> wave1_restricted <span class="sc">%&gt;%</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(age <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a> <span class="co"># scatter plot: Kessler Score vs. Age</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wave1_restricted, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> kessler_score)) <span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span>  <span class="co"># Transparency to avoid overplotting</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span>  <span class="co"># Linear trend line</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship Between Age and Depression (Restricted Data)"</span>,</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kessler Score (Depression)"</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GRPL2.0_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># correlation test: Age vs. Depression</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(wave1_restricted<span class="sc">$</span>age, wave1_restricted<span class="sc">$</span>kessler_score, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  wave1_restricted$age and wave1_restricted$kessler_score
t = 10.849, df = 6641, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1082623 0.1555214
sample estimates:
      cor 
0.1319668 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># apply linear regression: Predicting depression based on age</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>model.age <span class="ot">&lt;-</span> <span class="fu">lm</span>(kessler_score <span class="sc">~</span> age, <span class="at">data =</span> wave1_restricted)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kessler_score ~ age, data = wave1_restricted)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.4193  -4.9883  -0.7857   3.9923  30.0117 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 17.759895   0.242060   73.37   &lt;2e-16 ***
age          0.050646   0.004668   10.85   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.245 on 6641 degrees of freedom
  (27 observations deleted due to missingness)
Multiple R-squared:  0.01742,   Adjusted R-squared:  0.01727 
F-statistic: 117.7 on 1 and 6641 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div></li>
<li><p><em>Evaluating the RCT</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># summary statistics for Kessler Score by treatment group</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>wave1 <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treat_hh) <span class="sc">%&gt;%</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_kessler =</span> <span class="fu">mean</span>(kessler_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_kessler =</span> <span class="fu">median</span>(kessler_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_kessler =</span> <span class="fu">sd</span>(kessler_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>()</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  treat_hh                mean_kessler median_kessler sd_kessler count
  &lt;dbl+lbl&gt;                      &lt;dbl&gt;          &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
1 0 [Control household]           20.3             19       6.27  3713
2 1 [Treatment household]         20.4             20       6.35  3727</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># boxplot: Depression Score by Treatment Group</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wave1_restricted, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(treat_hh), <span class="at">y =</span> kessler_score, <span class="at">fill =</span> <span class="fu">factor</span>(treat_hh))) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Impact of Group Therapy on Depression (Wave 1)"</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Treatment Group (0 = Control, 1 = Treated)"</span>,</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kessler Score (Depression)"</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkred"</span>, <span class="st">"darkblue"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Treatment"</span>)) <span class="sc">+</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GRPL2.0_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># conduct T-test: Difference in Depression Scores Between Control and Treatment</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(kessler_score <span class="sc">~</span> treat_hh, <span class="at">data =</span> wave1_restricted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  kessler_score by treat_hh
t = -0.51425, df = 6641, p-value = 0.6071
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.3825464  0.2235507
sample estimates:
mean in group 0 mean in group 1 
       20.21098        20.29047 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># apply ;inear regression: Effect of treatment on depression</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>model.treat1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kessler_score <span class="sc">~</span> treat_hh, <span class="at">data =</span> wave1_restricted)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.treat1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kessler_score ~ treat_hh, data = wave1_restricted)

Residuals:
    Min      1Q  Median      3Q     Max 
-10.290  -5.211  -1.211   3.789  29.709 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  20.2110     0.1097 184.278   &lt;2e-16 ***
treat_hh      0.0795     0.1546   0.514    0.607    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.3 on 6641 degrees of freedom
  (27 observations deleted due to missingness)
Multiple R-squared:  3.981e-05, Adjusted R-squared:  -0.0001108 
F-statistic: 0.2644 on 1 and 6641 DF,  p-value: 0.6071</code></pre>
</div>
</div></li>
</ol>
<p><em>Using Wave 2 data to measure outcomes, answer the following questions, explaining any decisions and assumptions you make, and interpret your results. There is no need for you to address the validity of the random assignment of the intervention.</em></p>
</section>
<section id="q2-1" class="level2">
<h2 class="anchored" data-anchor-id="q2-1">Q2:</h2>
<p><em>Were the GT sessions effective at reducing depression?</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># first, filter for Wave 2 data</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>wave2<span class="ot">&lt;-</span> mergedv2 <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(wave <span class="sc">==</span> <span class="dv">2</span>) </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># check summary statistics of Kessler Score by treatment group in Wave 2</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>wave2 <span class="sc">%&gt;%</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(treat_hh) <span class="sc">%&gt;%</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_kessler =</span> <span class="fu">mean</span>(kessler_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_kessler =</span> <span class="fu">median</span>(kessler_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_kessler =</span> <span class="fu">sd</span>(kessler_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>()</span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  treat_hh                mean_kessler median_kessler sd_kessler count
  &lt;dbl+lbl&gt;                      &lt;dbl&gt;          &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
1 0 [Control household]           17.5             17       5.59  3190
2 1 [Treatment household]         17.0             16       5.35  3192</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot: Depression Score by Treatment Group (Wave 2)</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wave2, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(treat_hh), <span class="at">y =</span> kessler_score, <span class="at">fill =</span> <span class="fu">factor</span>(treat_hh))) <span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Impact of Group Therapy on Depression (Wave 2)"</span>,</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Treatment Group (0 = Control, 1 = Treated)"</span>,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kessler Score (Depression)"</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkred"</span>, <span class="st">"darkblue"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Treatment"</span>)) <span class="sc">+</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GRPL2.0_files/figure-html/part2q2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># next conduct T-test: Difference in Depression Scores Between Control and Treatment (Wave 2)</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(kessler_score <span class="sc">~</span> treat_hh, <span class="at">data =</span> wave2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  kessler_score by treat_hh
t = 3.8796, df = 6367.5, p-value = 0.0001057
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 0.2626988 0.7993474
sample estimates:
mean in group 0 mean in group 1 
       17.51285        16.98183 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># finally aplly linear regression: Effect of treatment on depression (Wave 2)</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>model.GT <span class="ot">&lt;-</span> <span class="fu">lm</span>(kessler_score <span class="sc">~</span> treat_hh, <span class="at">data =</span> wave2)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.GT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kessler_score ~ treat_hh, data = wave2)

Residuals:
   Min     1Q Median     3Q    Max 
-7.513 -3.982 -0.982  3.487 32.487 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  17.5129     0.0968  180.92  &lt; 2e-16 ***
treat_hh     -0.5310     0.1369   -3.88 0.000106 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.467 on 6380 degrees of freedom
Multiple R-squared:  0.002354,  Adjusted R-squared:  0.002197 
F-statistic: 15.05 on 1 and 6380 DF,  p-value: 0.0001057</code></pre>
</div>
</div>
</section>
<section id="q3-1" class="level2">
<h2 class="anchored" data-anchor-id="q3-1">Q3:</h2>
<p><em>Did the effect of GT sessions on depression differ by gender? Perform a linear regression of the Kessler Score on:</em></p>
<ul>
<li><p><em>Woman (binary variable)</em></p></li>
<li><p><em>Treated Household (binary variable)</em></p></li>
<li><p><em>Interaction term: Treated Household * Woman, using only Wave 2 observations.</em></p></li>
</ul>
<p><em>Note: Note: In your write-up for this question, please make sure to explain and interpret all coefficients in your specification, keeping in mind units and reference groups.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># first create binary variable for Woman (assuming 1 = male, 5 = female)</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>wave2_gender<span class="ot">&lt;-</span> wave2 <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">woman =</span> <span class="fu">ifelse</span>(gender <span class="sc">==</span> <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">0</span>))  </span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># next apply linear regression: testing interaction between treatment and gender</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>model.genderINT <span class="ot">&lt;-</span> <span class="fu">lm</span>(kessler_score <span class="sc">~</span> treat_hh <span class="sc">*</span> woman, <span class="at">data =</span> wave2_gender)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.genderINT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kessler_score ~ treat_hh * woman, data = wave2_gender)

Residuals:
   Min     1Q Median     3Q    Max 
-7.859 -4.021 -0.932  3.141 32.141 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     17.0634     0.1466 116.411  &lt; 2e-16 ***
treat_hh        -0.1319     0.2068  -0.638   0.5237    
woman            0.7956     0.1950   4.080 4.56e-05 ***
treat_hh:woman  -0.7059     0.2756  -2.561   0.0105 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.461 on 6378 degrees of freedom
Multiple R-squared:  0.004983,  Adjusted R-squared:  0.004515 
F-statistic: 10.65 on 3 and 6378 DF,  p-value: 5.586e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a> <span class="co"># visualization: Effect of treatment by gender</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(wave2_gender, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(treat_hh), <span class="at">y =</span> kessler_score, <span class="at">fill =</span> <span class="fu">factor</span>(woman))) <span class="sc">+</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Effect of Group Therapy on Depression by Gender (Wave 2)"</span>,</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Treatment Group (0 = Control, 1 = Treated)"</span>,</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Kessler Score (Depression)"</span>,</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Gender (0 = Male, 1 = Female)"</span></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkred"</span>, <span class="st">"darkblue"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>)) <span class="sc">+</span></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GRPL2.0_files/figure-html/part2q3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="summary-of-results" class="level1">
<h1><strong>Summary of Results</strong></h1>
<p><em>Present your results as you see fit and add a write-up with your interpretation and conclusions.</em></p>
<section id="results-q1---asset-value" class="level2">
<h2 class="anchored" data-anchor-id="results-q1---asset-value">Results Q1 - Asset Value</h2>
<p><strong>Key Findings (Full Data, Before Restriction)</strong></p>
<ul>
<li><p><strong>Correlation Analysis:</strong></p>
<ul>
<li><p>The correlation between&nbsp;total asset value (household wealth proxy) and depression (Kessler-10 score)was very weak and statistically insignificant (cor=−0.004, p=0.728).</p></li>
<li><p>This suggests that&nbsp;wealth does not meaningfully predict depression in the full sample.</p></li>
</ul></li>
<li><p><strong>Linear Regression Results:</strong></p>
<ul>
<li><p>The&nbsp;total asset value coefficient&nbsp;was&nbsp;not significant (effect =−2.14e-7, p=.728).</p></li>
<li><p>The r-squared value was nearly zero, meaning that&nbsp;household wealth explains almost none of the variation in depression.</p></li>
</ul></li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li>There is&nbsp;no meaningful relationship between household wealth and depression&nbsp;when analyzing the full dataset.</li>
</ul>
<p><em>I thought an interesting adjustment may be to check the relationship by restricting the data, removing observations above 90th percentile in total asset value.</em></p>
<p><strong>Key Findings (Restricted Data: Removing Top 10% Wealthiest Households)</strong></p>
<ul>
<li><p><strong>Summary Statistics After Restriction:</strong></p>
<ul>
<li>The maximum <strong>total asset value</strong>&nbsp;was <strong>12,069</strong>&nbsp;currency units, compared to <strong>5.79 million</strong> in the full dataset, removes extreme wealth values that may introduce bias.</li>
</ul></li>
<li><p><strong>Correlation Analysis:</strong></p>
<ul>
<li><p>Interestingly, the correlation became negative and statistically significant (cor=−0.038, p=0.002).</p></li>
<li><p>This suggests that higher household wealth is now slightly associated with lower depression scores.</p></li>
</ul></li>
<li><p><strong>Linear Regression Results:</strong></p>
<ul>
<li><p>The total asset value coefficient was negative and significant (effect=−9.8e-5,&nbsp;p=0.002).</p></li>
<li><p>Effect size is very small, but it implies that an increase in wealth corresponds to a slight decrease in depression.</p></li>
</ul></li>
</ul>
<p>I<strong>nterpretation:</strong></p>
<ul>
<li>After removing the wealthiest 10% of households, a small but statistically significant negative relationship emerges between wealth and depression. This suggests that for most households, increased wealth is weakly associated with better mental health. However, the effect remains minimal, meaning other social and psychological factors likely play a larger role in depression in Ghana than economic status.</li>
</ul>
</section>
<section id="results-q1---age" class="level2">
<h2 class="anchored" data-anchor-id="results-q1---age">Results Q1 - Age</h2>
<section id="findings" class="level4">
<h4 class="anchored" data-anchor-id="findings"><strong>Findings:</strong></h4>
<ul>
<li><p><strong>Correlation Analysis:</strong>&nbsp;There was a weak but statistically significant positive correlation&nbsp;between age and depression (cor= 0.128 p&lt;0.001). This suggests that older individuals tend to report higher depression scores.</p></li>
<li><p><strong>Linear Regression:</strong>&nbsp;Age was a significant predictor of depression (effect = 0.049, p&lt;0.001), meaning that each additional year of age is associated with a 0.05 point increase in depression score.</p></li>
<li><p><strong>Scatter Plot Analysis:</strong>&nbsp;The <strong>positive trend</strong> in the scatterplot supports this conclusion.</p></li>
</ul>
</section>
<section id="interpretation" class="level4">
<h4 class="anchored" data-anchor-id="interpretation"><strong>Interpretation:</strong></h4>
<ul>
<li><p>Older individuals in Ghana&nbsp;tend to report higher depression levels, possibly due to reduced social engagement, health deterioration, or financial insecurity in later life.</p></li>
<li><p>The effect, though small, is statistically significant, suggesting that age should be considered in mental health interventions.</p></li>
</ul>
</section>
</section>
<section id="results-q1---rct" class="level2">
<h2 class="anchored" data-anchor-id="results-q1---rct">Results Q1 - RCT</h2>
<p><strong>Findings (Pre-Treatment Comparison in Wave 1)</strong></p>
<ul>
<li><p><strong>Descriptive Statistics</strong></p>
<ul>
<li><p>The&nbsp;mean Kessler-10 score&nbsp;in&nbsp;control households:&nbsp;20.31</p></li>
<li><p>The&nbsp;mean Kessler-10 score&nbsp;in&nbsp;treatment households:&nbsp;20.36</p></li>
<li><p>The&nbsp;difference in means is only 0.05 points, which is&nbsp;very small.</p></li>
</ul></li>
<li><p><strong>T-Test Results:</strong></p>
<ul>
<li>The&nbsp;p-value = 0.7433, meaning&nbsp;there is <strong>no</strong> statistically significant difference&nbsp;in depression scores before treatment.</li>
</ul></li>
<li><p><strong>Linear Regression:</strong></p>
<ul>
<li>The&nbsp;<strong>t</strong>reatment group indicator is <strong>not</strong> statistically significant p =0.743), confirming that&nbsp;depression levels were similar in both groups before therapy.</li>
</ul></li>
</ul>
<p><strong>Interpretation:</strong></p>
<p>Randomization worked: Before treatment, there was&nbsp;no meaningful difference in depression scores between control and treatment households.<br>
This ensures that any differences observed in Wave 2 are due to Group Therapy&nbsp;and&nbsp;not pre-existing differences between groups.</p>
</section>
<section id="results-q2---group-therapy-effect" class="level2">
<h2 class="anchored" data-anchor-id="results-q2---group-therapy-effect">Results Q2 - Group Therapy Effect</h2>
<ul>
<li><p><strong>Descriptive Statistics:</strong></p>
<ul>
<li><p>The&nbsp;mean Kessler-10 score&nbsp;in&nbsp;control households&nbsp;(no therapy) was&nbsp;17.51.</p></li>
<li><p>The&nbsp;mean Kessler-10 score&nbsp;in&nbsp;treatment households&nbsp;(received therapy) was&nbsp;16.98.</p></li>
</ul></li>
<li><p><strong>T-Test Results:</strong>&nbsp;The difference in depression scores between the control and treatment groups was&nbsp;<strong>statistically significant</strong> p&lt;0.001), indicating lower depression in treatment households.</p></li>
<li><p><strong>Linear Regression:</strong></p>
<ul>
<li><p>Belonging to a&nbsp;<strong>treatment household</strong> was associated with a <strong>0.53-point decrease</strong>&nbsp;in depression scores with an effect size of 0.531, p&lt;0.001).</p></li>
<li><p>The effect size is small but meaningful.</p></li>
</ul></li>
</ul>
</section>
<section id="results-q3---gender-effect" class="level2">
<h2 class="anchored" data-anchor-id="results-q3---gender-effect">Results Q3 - Gender Effect</h2>
<p>To explore whether therapy affected&nbsp;men and women differently, we introduced an interaction term in the regression model.</p>
<section id="findings-1" class="level4">
<h4 class="anchored" data-anchor-id="findings-1"><strong>Findings:</strong></h4>
<ul>
<li><p><strong>Main effects:</strong></p>
<ul>
<li><p>Being female <strong>was</strong> associated with&nbsp;higher depression scores =0.796, p &lt; 0.001), meaning&nbsp;women experienced more depressive symptoms than men&nbsp;on average.</p></li>
<li><p>Belonging to a treatment household alone was not statistically significant (p=0.524), suggesting that GT alone <strong>did not</strong> impact depression when gender isn't accounted for.</p></li>
</ul></li>
<li><p><strong>Interaction Effect:</strong></p>
<ul>
<li>The interaction term effect =−0.706, p=0.011) <strong>was</strong> statistically significant, meaning the effect of GT on depression was stronger for women.</li>
</ul></li>
<li><p><strong>Visualization:</strong>&nbsp;The boxplot showed a clearer reduction in depression among treated women compared to treated men.</p></li>
</ul>
</section>
<section id="interpretation-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-1"><strong>Interpretation:</strong></h4>
<ul>
<li>Women in Ghana experience more depression than men. Group Therapy was more effective for women, reducing their depression scores significantly. This suggests gender-sensitive mental health interventions may be needed, as women benefit more from these socially structured interventions according to our data.</li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>